CREATE TABLE IF NOT EXISTS elec_trade_data_tw (
    id SERIAL PRIMARY KEY,
    tran_date DATE NOT NULL,
    tran_hour TIME NOT NULL,
    marginal_price NUMERIC(10, 3),
    reg_bid NUMERIC(10, 3),
    reg_bid_qse NUMERIC(10, 3),
    reg_bid_nontrade NUMERIC(10, 3),
    reg_demand NUMERIC(10, 3),
    reg_offering NUMERIC(10, 3),
    reg_price NUMERIC(10, 3),
    reg_registered NUMERIC(10, 3),
    sr_bid NUMERIC(10, 3),
    sr_bid_qse NUMERIC(10, 3),
    sr_bid_nontrade NUMERIC(10, 3),
    sr_demand NUMERIC(10, 3),
    sr_offering NUMERIC(10, 3),
    sr_price NUMERIC(10, 3),
    sr_registered NUMERIC(10, 3),
    sup_bid NUMERIC(10, 3),
    sup_bid_qse NUMERIC(10, 3),
    sup_bid_nontrade NUMERIC(10, 3),
    sup_demand NUMERIC(10, 3),
    sup_offering NUMERIC(10, 3),
    sup_price NUMERIC(10, 3),
    sup_registered NUMERIC(10, 3),
    edreg_bid NUMERIC(10, 3),
    edreg_price NUMERIC(10, 3),
    created_at timestamp WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'utc'),
    CONSTRAINT elec_trade_data_tw_unique UNIQUE (tran_date, tran_hour)
);
